version: "3"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    container_name: es01
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - indices.query.bool.max_clause_count=1000000
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata/data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4JLABS_PLUGINS=["apoc"] 
    volumes:
      - ./neo4j/db/plugins:/plugins
      - ./neo4j/db/data:/data
      - ./neo4j/db/import:/import
    env_file: 
      .env

volumes:
  data01:
  plugins:
  data:
  import:

networks:
  elastic: